name: migrated-continue-config
version: 0.0.1
schema: v1

models:
  - name: Ollama
    provider: ollama
    model: AUTODETECT
    apiBase: http://192.168.2.23:11434
    defaultCompletionOptions:
      topP: 0.7
      maxTokens: 4096
    roles:
      - chat
      - edit
      - apply

  - name: qllama/bge-reranker-v2-m3
    provider: ollama
    model: qllama/bge-reranker-v2-m3
    apiBase: http://192.168.2.23:11434
    roles:
      - rerank

  - name: dengcao/Qwen3-Reranker-0.6B:Q8_0
    provider: ollama
    model: dengcao/Qwen3-Reranker-0.6B:Q8_0
    apiBase: http://192.168.2.23:11434
    roles:
      - rerank

  - name: qwen2.5-coder:1.5b
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://192.168.2.23:11434
    roles:
      - autocomplete

  - name: nomic-embed-text
    provider: ollama
    model: nomic-embed-text
    apiBase: http://192.168.2.23:11434
    roles:
      - embed

prompts:
  - name: js/ts
    description: prompt for JavaScript/TypeScript developers
    prompt: |
      You are an expert in web developing. You are specialize in JS/TS.

      You need to provide short response.

      You need to do it in several steps:

      1. Analyze request

      2. ask clarify questions

      3. suggest improvment

      4. Ask about feadback

      5. provide definitive response

      {{{ input }}}

context:
  - provider: terminal
  - provider: repo-map
    params:
      includeSignatures: false # default true